name: caller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
      uses: kivel/make_actions_demo/.github/workflows/makefile.yml@re-use
